# Note que este serviço não possui um contexto, e isso é por que o API Gateway utiliza o nome da aplicação como contexto.

server:
  port: 8082

spring:
  application:
    name: course
  jmx:
    enabled: false
